export const skills = [
  "HTML",
  "CSS",
  "Flex",
  "Grid",
  "BEM ",
  "Git",
  "Github Pull Requests & Review",
  "JavaScript:ES6+",
  "React",
  "React Hooks",
  "React-Router",
  "Redux",
  "Redux-Saga",
  "Promises,Async/Await",
];
