export const skills = [
  "HTML",
  "CSS",
  "CSS Flexbox",
  "CSS Grid",
  "CSS BEM convention",
  "Git",
  "Github Pull Requests & Review",
  "JavaScript:ES6+",
  "React",
  "React Hooks",
  "React-Router",
  "Redux",
  "Redux-Saga",
  "Promises,Async/Await",
];
